@startuml
' SSD – UC1 Register User

autonumber

actor "User" as user
participant System as sys


user -> sys: Selects "Register"
sys --> user: Requests registration data\n(Name, Email, Password)
user -> sys: Provides typed data

sys -> sys: Validate data
alt Data is valid
  sys --> user: Informs operation success\n(Account created)
else Data is invalid
  sys --> user: Informs operation failure\n(Invalid data)
end

@enduml
