@startuml
' SSD – UC15 Mark Reminder as Completed
autonumber

actor "User" as user
participant System as sys

user -> sys: Selects "Todos" reminder container
user -> sys: Marks as completed
sys --> user: Sends lembretes to "Concluidos" remainder container

@enduml
